### ISSUE TITLE
Vision Model Request

### ISSUE THREAD

**Issue by kueckermann** [Pelochus/ezrknpu#7]
Amazing work! Any chance of a converted vision model? Perhaps Moondream2 1.8B or LLaVA 7B model?

**Comment by Pelochus** [comment]
AFAIK it is not possible to run vision LLMs (check rknn-llm README). There is capability to run CV models like Yolo with rknn-toolkit2 though.

**Comment by kueckermann** [comment]
Thanks @Pelochus for the fast response. I had a look over rknn-llm README, was it because it only supports the models under the Support Models section or was there some other limitation I missed that would prevent a vision model from working?

**Comment by Pelochus** [comment]
Yeah, since it is closed source is as you say: only support for whatever Rockchip develops for. In this case the list is (as you've probably read in the README):

[TinyLLAMA 1.1B](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0/tree/fe8a4ea1ffedaf415f4da2f062534de366a451e6)
[Qwen 1.8B](https://huggingface.co/Qwen/Qwen-1_8B-Chat/tree/1d0f68de57b88cfde81f3c3e537f24464d889081)
[Qwen2 0.5B](https://huggingface.co/Qwen/Qwen1.5-0.5B/tree/8f445e3628f3500ee69f24e1303c9f10f5342a39)
[Phi-2 2.7B](https://hf-mirror.com/microsoft/phi-2/tree/834565c23f9b28b96ccbeabe614dd906b6db551a)
[Phi-3 3.8B](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/tree/291e9e30e38030c23497afa30f3af1f104837aa6)
[ChatGLM3 6B](https://huggingface.co/THUDM/chatglm3-6b/tree/103caa40027ebfd8450289ca2f278eac4ff26405)
[Gemma 2B](https://huggingface.co/google/gemma-2b-it/tree/de144fb2268dee1066f515465df532c05e699d48)
[InternLM2 1.8B](https://huggingface.co/internlm/internlm2-chat-1_8b/tree/ecccbb5c87079ad84e5788baa55dd6e21a9c614d)
[MiniCPM 2B](https://huggingface.co/openbmb/MiniCPM-2B-sft-bf16/tree/79fbb1db171e6d8bf77cdb0a94076a43003abd9e)
